[package]
name = "yafetch"
version = "0.0.2"
edition = "2024"
[dependencies]
sysinfo = "0.38.2"
colored = "3.1.1"
[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = 'abort'
strip = true
